name: Build and Push snapshot image
on:
  workflow_dispatch:
  push:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/maain'
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Build and Publish Tag Docker image
          uses: VaultVulp/gp-docker-action@1.6.0
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              image-name: transmission
              image-tag: snapshot
